/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat (TomEE)/7.0.55 (1.7.1)
 * Generated at: 2015-05-22 16:09:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fview;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fform;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fcommandLink_0026_005fvalue_005faction_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fcommandLink_0026_005fvalue_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fparam_0026_005fvalue_005fname_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ff_005fview = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fform = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fcommandLink_0026_005fvalue_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fcommandLink_0026_005fvalue_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005fparam_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ff_005fview.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fh_005fform.release();
    _005fjspx_005ftagPool_005fh_005fcommandLink_0026_005fvalue_005faction_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005fcommandLink_0026_005fvalue_005faction.release();
    _005fjspx_005ftagPool_005ff_005fparam_0026_005fvalue_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=US-ASCII");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<body bgcolor=\"#E6E6FA\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=US-ASCII\">\n");
      out.write("<title>SIW-PROGETTO-ESAME</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");
      if (_jspx_meth_f_005fview_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_f_005fview_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:view
    org.apache.myfaces.taglib.core.ViewTag _jspx_th_f_005fview_005f0 = (new org.apache.myfaces.taglib.core.ViewTag());
    _jsp_instancemanager.newInstance(_jspx_th_f_005fview_005f0);
    _jspx_th_f_005fview_005f0.setPageContext(_jspx_page_context);
    _jspx_th_f_005fview_005f0.setParent(null);
    _jspx_th_f_005fview_005f0.setJspId("jsp_20032806_0");
    int _jspx_eval_f_005fview_005f0 = _jspx_th_f_005fview_005f0.doStartTag();
    if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_f_005fview_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_f_005fview_005f0.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t\t<h1><center>PROGETTO ESAME SIW GIUGNO 2014</center></h1>\n");
        out.write("\t\t\n");
        out.write("\t\t<h1><center>Benvenuto ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${amministratoreController.corrente.mail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${utenteController.corrente.mail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write('\n');
        out.write('	');
        out.write('	');
        if (_jspx_meth_c_005fif_005f0(_jspx_th_f_005fview_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        out.write('	');
        out.write('	');
        if (_jspx_meth_c_005fif_005f1(_jspx_th_f_005fview_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t</center></h1>\n");
        out.write("\t\t\n");
        out.write("\t\t");
        if (_jspx_meth_c_005fif_005f2(_jspx_th_f_005fview_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        out.write('	');
        out.write('	');
        if (_jspx_meth_c_005fif_005f3(_jspx_th_f_005fview_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\n");
        out.write("\t\t");
        if (_jspx_meth_c_005fif_005f4(_jspx_th_f_005fview_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        out.write('	');
        out.write('	');
        if (_jspx_meth_c_005fif_005f5(_jspx_th_f_005fview_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        out.write('	');
        out.write('	');
        if (_jspx_meth_c_005fif_005f6(_jspx_th_f_005fview_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\n");
        out.write("\t\t<h2>Operazioni per la diagnostica:</h2> \n");
        out.write("\t\t<ul>\n");
        out.write("\t\t\t<li><a href='");
        if (_jspx_meth_c_005furl_005f5(_jspx_th_f_005fview_005f0, _jspx_page_context))
          return true;
        out.write("'>Inserisci un nuovo prodotto nella base di dati</a></li>\n");
        out.write("\t\t\t<li>");
        if (_jspx_meth_h_005fform_005f9(_jspx_th_f_005fview_005f0, _jspx_page_context))
          return true;
        out.write("</li>\n");
        out.write("\t\t\t<li><a href='");
        if (_jspx_meth_c_005furl_005f6(_jspx_th_f_005fview_005f0, _jspx_page_context))
          return true;
        out.write("'>Inserisci un nuovo amministratore nella base di dati</a></li>\n");
        out.write("\t\t</ul>\n");
        out.write("\t\t<h2>Realizzato dagli studenti:</h2>\n");
        out.write("\t\t<ul>\n");
        out.write("\t\t\t<li>Brutti Davide</li>\n");
        out.write("\t\t\t<li>Germano Lorenzo</li>\n");
        out.write("\t\t</ul>\n");
        out.write("\t\t<h2><a href=\"https://github.com/sorcio46/SIW_Esercitazioni/\">Repository del progetto su Github</a></h2> \n");
        out.write("\t");
        int evalDoAfterBody = _jspx_th_f_005fview_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_f_005fview_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_f_005fview_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_f_005fview_005f0);
      return true;
    }
    _jspx_th_f_005fview_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_f_005fview_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
    // /index.jsp(18,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${amministratoreController.corrente != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t");
        if (_jspx_meth_h_005fform_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        out.write('	');
        out.write('	');
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:form
    org.apache.myfaces.taglib.html.HtmlFormTag _jspx_th_h_005fform_005f0 = (new org.apache.myfaces.taglib.html.HtmlFormTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fform_005f0);
    _jspx_th_h_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_h_005fform_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    _jspx_th_h_005fform_005f0.setJspId("jsp_20032806_1");
    int _jspx_eval_h_005fform_005f0 = _jspx_th_h_005fform_005f0.doStartTag();
    if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005fform_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005fform_005f0.doInitBody();
      }
      do {
        if (_jspx_meth_h_005fcommandLink_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_h_005fform_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fform_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f0);
      return true;
    }
    _jspx_th_h_005fform_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f0);
    return false;
  }

  private boolean _jspx_meth_h_005fcommandLink_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandLink
    org.apache.myfaces.taglib.html.HtmlCommandLinkTag _jspx_th_h_005fcommandLink_005f0 = (new org.apache.myfaces.taglib.html.HtmlCommandLinkTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fcommandLink_005f0);
    _jspx_th_h_005fcommandLink_005f0.setPageContext(_jspx_page_context);
    _jspx_th_h_005fcommandLink_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
    // /index.jsp(19,11) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object myMethod(  )
    _jspx_th_h_005fcommandLink_005f0.setAction(new org.apache.jasper.el.JspMethodExpression("/index.jsp(19,11) '#{amministratoreController.logoutAmministratore}'",_el_expressionfactory.createMethodExpression(_jspx_page_context.getELContext(),"#{amministratoreController.logoutAmministratore}",java.lang.Object.class,new java.lang.Class[] {})));
    // /index.jsp(19,11) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005fcommandLink_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/index.jsp(19,11) 'LOGOUT'",_el_expressionfactory.createValueExpression("LOGOUT",java.lang.Object.class)));
    _jspx_th_h_005fcommandLink_005f0.setJspId("jsp_20032806_2");
    int _jspx_eval_h_005fcommandLink_005f0 = _jspx_th_h_005fcommandLink_005f0.doStartTag();
    if (_jspx_th_h_005fcommandLink_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fcommandLink_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f0);
      return true;
    }
    _jspx_th_h_005fcommandLink_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
    // /index.jsp(21,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${utenteController.corrente != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t");
        if (_jspx_meth_h_005fform_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        out.write('\n');
        out.write('	');
        out.write('	');
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:form
    org.apache.myfaces.taglib.html.HtmlFormTag _jspx_th_h_005fform_005f1 = (new org.apache.myfaces.taglib.html.HtmlFormTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fform_005f1);
    _jspx_th_h_005fform_005f1.setPageContext(_jspx_page_context);
    _jspx_th_h_005fform_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    _jspx_th_h_005fform_005f1.setJspId("jsp_20032806_3");
    int _jspx_eval_h_005fform_005f1 = _jspx_th_h_005fform_005f1.doStartTag();
    if (_jspx_eval_h_005fform_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005fform_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005fform_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005fform_005f1.doInitBody();
      }
      do {
        if (_jspx_meth_h_005fcommandLink_005f1(_jspx_th_h_005fform_005f1, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_h_005fform_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005fform_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005fform_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fform_005f1.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f1);
      return true;
    }
    _jspx_th_h_005fform_005f1.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f1);
    return false;
  }

  private boolean _jspx_meth_h_005fcommandLink_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandLink
    org.apache.myfaces.taglib.html.HtmlCommandLinkTag _jspx_th_h_005fcommandLink_005f1 = (new org.apache.myfaces.taglib.html.HtmlCommandLinkTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fcommandLink_005f1);
    _jspx_th_h_005fcommandLink_005f1.setPageContext(_jspx_page_context);
    _jspx_th_h_005fcommandLink_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f1);
    // /index.jsp(22,11) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object myMethod(  )
    _jspx_th_h_005fcommandLink_005f1.setAction(new org.apache.jasper.el.JspMethodExpression("/index.jsp(22,11) '#{utenteController.logoutUtente}'",_el_expressionfactory.createMethodExpression(_jspx_page_context.getELContext(),"#{utenteController.logoutUtente}",java.lang.Object.class,new java.lang.Class[] {})));
    // /index.jsp(22,11) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005fcommandLink_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/index.jsp(22,11) 'LOGOUT'",_el_expressionfactory.createValueExpression("LOGOUT",java.lang.Object.class)));
    _jspx_th_h_005fcommandLink_005f1.setJspId("jsp_20032806_4");
    int _jspx_eval_h_005fcommandLink_005f1 = _jspx_th_h_005fcommandLink_005f1.doStartTag();
    if (_jspx_th_h_005fcommandLink_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fcommandLink_005f1.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f1);
      return true;
    }
    _jspx_th_h_005fcommandLink_005f1.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
    // /index.jsp(26,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${amministratoreController.corrente == null && utenteController.corrente == null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t<h1><center>Non sei registrato? Chiedi a un Amministratore!</center></h1>\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
    // /index.jsp(29,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${amministratoreController.corrente == null && utenteController.corrente==null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t<h1><center>");
        if (_jspx_meth_h_005fform_005f2(_jspx_th_c_005fif_005f3, _jspx_page_context))
          return true;
        out.write("</center></h1>\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:form
    org.apache.myfaces.taglib.html.HtmlFormTag _jspx_th_h_005fform_005f2 = (new org.apache.myfaces.taglib.html.HtmlFormTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fform_005f2);
    _jspx_th_h_005fform_005f2.setPageContext(_jspx_page_context);
    _jspx_th_h_005fform_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
    _jspx_th_h_005fform_005f2.setJspId("jsp_20032806_5");
    int _jspx_eval_h_005fform_005f2 = _jspx_th_h_005fform_005f2.doStartTag();
    if (_jspx_eval_h_005fform_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005fform_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005fform_005f2.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005fform_005f2.doInitBody();
      }
      do {
        if (_jspx_meth_h_005fcommandLink_005f2(_jspx_th_h_005fform_005f2, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_h_005fform_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005fform_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005fform_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fform_005f2.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f2);
      return true;
    }
    _jspx_th_h_005fform_005f2.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f2);
    return false;
  }

  private boolean _jspx_meth_h_005fcommandLink_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandLink
    org.apache.myfaces.taglib.html.HtmlCommandLinkTag _jspx_th_h_005fcommandLink_005f2 = (new org.apache.myfaces.taglib.html.HtmlCommandLinkTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fcommandLink_005f2);
    _jspx_th_h_005fcommandLink_005f2.setPageContext(_jspx_page_context);
    _jspx_th_h_005fcommandLink_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f2);
    // /index.jsp(30,23) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object myMethod(  )
    _jspx_th_h_005fcommandLink_005f2.setAction(new org.apache.jasper.el.JspMethodExpression("/index.jsp(30,23) '#{productController.listProducts}'",_el_expressionfactory.createMethodExpression(_jspx_page_context.getELContext(),"#{productController.listProducts}",java.lang.Object.class,new java.lang.Class[] {})));
    // /index.jsp(30,23) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005fcommandLink_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/index.jsp(30,23) 'Visita il nostro Catalogo Prodotti'",_el_expressionfactory.createValueExpression("Visita il nostro Catalogo Prodotti",java.lang.Object.class)));
    _jspx_th_h_005fcommandLink_005f2.setJspId("jsp_20032806_6");
    int _jspx_eval_h_005fcommandLink_005f2 = _jspx_th_h_005fcommandLink_005f2.doStartTag();
    if (_jspx_th_h_005fcommandLink_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fcommandLink_005f2.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f2);
      return true;
    }
    _jspx_th_h_005fcommandLink_005f2.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
    // /index.jsp(33,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${amministratoreController.corrente != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
    if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t<h1><center>");
        if (_jspx_meth_h_005fform_005f3(_jspx_th_c_005fif_005f4, _jspx_page_context))
          return true;
        out.write("</center></h1>\n");
        out.write("\t\t\t<h1><center><a href='");
        if (_jspx_meth_c_005furl_005f0(_jspx_th_c_005fif_005f4, _jspx_page_context))
          return true;
        out.write("'>Inserisci un prodotto nel catalogo</a></center></h1>\n");
        out.write("\t\t\t\n");
        out.write("\t\t\t<h1><center>\n");
        out.write("\t\t\t");
        if (_jspx_meth_h_005fform_005f4(_jspx_th_c_005fif_005f4, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t</center></h1>\n");
        out.write("\t\t\t\n");
        out.write("\t\t\t<h1><center>\n");
        out.write("\t\t\t");
        if (_jspx_meth_h_005fform_005f5(_jspx_th_c_005fif_005f4, _jspx_page_context))
          return true;
        out.write("</center></h1>\n");
        out.write("\t\t\t\n");
        out.write("\t\t\t<h1><center><a href='");
        if (_jspx_meth_c_005furl_005f1(_jspx_th_c_005fif_005f4, _jspx_page_context))
          return true;
        out.write("'>Registra Utente</a></center></h1>\n");
        out.write("\t\t\t<h1><center><a href='");
        if (_jspx_meth_c_005furl_005f2(_jspx_th_c_005fif_005f4, _jspx_page_context))
          return true;
        out.write("'>Registra un Fornitore</a></center></h1>\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:form
    org.apache.myfaces.taglib.html.HtmlFormTag _jspx_th_h_005fform_005f3 = (new org.apache.myfaces.taglib.html.HtmlFormTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fform_005f3);
    _jspx_th_h_005fform_005f3.setPageContext(_jspx_page_context);
    _jspx_th_h_005fform_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
    _jspx_th_h_005fform_005f3.setJspId("jsp_20032806_7");
    int _jspx_eval_h_005fform_005f3 = _jspx_th_h_005fform_005f3.doStartTag();
    if (_jspx_eval_h_005fform_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005fform_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005fform_005f3.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005fform_005f3.doInitBody();
      }
      do {
        if (_jspx_meth_h_005fcommandLink_005f3(_jspx_th_h_005fform_005f3, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_h_005fform_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005fform_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005fform_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fform_005f3.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f3);
      return true;
    }
    _jspx_th_h_005fform_005f3.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f3);
    return false;
  }

  private boolean _jspx_meth_h_005fcommandLink_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandLink
    org.apache.myfaces.taglib.html.HtmlCommandLinkTag _jspx_th_h_005fcommandLink_005f3 = (new org.apache.myfaces.taglib.html.HtmlCommandLinkTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fcommandLink_005f3);
    _jspx_th_h_005fcommandLink_005f3.setPageContext(_jspx_page_context);
    _jspx_th_h_005fcommandLink_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f3);
    // /index.jsp(34,23) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object myMethod(  )
    _jspx_th_h_005fcommandLink_005f3.setAction(new org.apache.jasper.el.JspMethodExpression("/index.jsp(34,23) '#{productController.listProductsAdmin}'",_el_expressionfactory.createMethodExpression(_jspx_page_context.getELContext(),"#{productController.listProductsAdmin}",java.lang.Object.class,new java.lang.Class[] {})));
    // /index.jsp(34,23) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005fcommandLink_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/index.jsp(34,23) 'Modifica il Catalogo Prodotti'",_el_expressionfactory.createValueExpression("Modifica il Catalogo Prodotti",java.lang.Object.class)));
    _jspx_th_h_005fcommandLink_005f3.setJspId("jsp_20032806_8");
    int _jspx_eval_h_005fcommandLink_005f3 = _jspx_th_h_005fcommandLink_005f3.doStartTag();
    if (_jspx_th_h_005fcommandLink_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fcommandLink_005f3.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f3);
      return true;
    }
    _jspx_th_h_005fcommandLink_005f3.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
    // /index.jsp(35,24) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/faces/newProduct.jsp");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:form
    org.apache.myfaces.taglib.html.HtmlFormTag _jspx_th_h_005fform_005f4 = (new org.apache.myfaces.taglib.html.HtmlFormTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fform_005f4);
    _jspx_th_h_005fform_005f4.setPageContext(_jspx_page_context);
    _jspx_th_h_005fform_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
    _jspx_th_h_005fform_005f4.setJspId("jsp_20032806_9");
    int _jspx_eval_h_005fform_005f4 = _jspx_th_h_005fform_005f4.doStartTag();
    if (_jspx_eval_h_005fform_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005fform_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005fform_005f4.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005fform_005f4.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_h_005fcommandLink_005f4(_jspx_th_h_005fform_005f4, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_h_005fform_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005fform_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005fform_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fform_005f4.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f4);
      return true;
    }
    _jspx_th_h_005fform_005f4.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f4);
    return false;
  }

  private boolean _jspx_meth_h_005fcommandLink_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandLink
    org.apache.myfaces.taglib.html.HtmlCommandLinkTag _jspx_th_h_005fcommandLink_005f4 = (new org.apache.myfaces.taglib.html.HtmlCommandLinkTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fcommandLink_005f4);
    _jspx_th_h_005fcommandLink_005f4.setPageContext(_jspx_page_context);
    _jspx_th_h_005fcommandLink_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f4);
    // /index.jsp(39,4) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object myMethod(  )
    _jspx_th_h_005fcommandLink_005f4.setAction(new org.apache.jasper.el.JspMethodExpression("/index.jsp(39,4) '#{ordineController.preparaEvasioneOrdini}'",_el_expressionfactory.createMethodExpression(_jspx_page_context.getELContext(),"#{ordineController.preparaEvasioneOrdini}",java.lang.Object.class,new java.lang.Class[] {})));
    // /index.jsp(39,4) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005fcommandLink_005f4.setValue(new org.apache.jasper.el.JspValueExpression("/index.jsp(39,4) 'Evadi Ordini'",_el_expressionfactory.createValueExpression("Evadi Ordini",java.lang.Object.class)));
    _jspx_th_h_005fcommandLink_005f4.setJspId("jsp_20032806_10");
    int _jspx_eval_h_005fcommandLink_005f4 = _jspx_th_h_005fcommandLink_005f4.doStartTag();
    if (_jspx_eval_h_005fcommandLink_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005fcommandLink_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005fcommandLink_005f4.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005fcommandLink_005f4.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_h_005fcommandLink_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005fcommandLink_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005fcommandLink_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fcommandLink_005f4.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f4);
      return true;
    }
    _jspx_th_h_005fcommandLink_005f4.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f4);
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:form
    org.apache.myfaces.taglib.html.HtmlFormTag _jspx_th_h_005fform_005f5 = (new org.apache.myfaces.taglib.html.HtmlFormTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fform_005f5);
    _jspx_th_h_005fform_005f5.setPageContext(_jspx_page_context);
    _jspx_th_h_005fform_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
    _jspx_th_h_005fform_005f5.setJspId("jsp_20032806_11");
    int _jspx_eval_h_005fform_005f5 = _jspx_th_h_005fform_005f5.doStartTag();
    if (_jspx_eval_h_005fform_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005fform_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005fform_005f5.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005fform_005f5.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t\t\t");
        if (_jspx_meth_h_005fcommandLink_005f5(_jspx_th_h_005fform_005f5, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_h_005fform_005f5.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005fform_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005fform_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fform_005f5.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f5);
      return true;
    }
    _jspx_th_h_005fform_005f5.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f5);
    return false;
  }

  private boolean _jspx_meth_h_005fcommandLink_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandLink
    org.apache.myfaces.taglib.html.HtmlCommandLinkTag _jspx_th_h_005fcommandLink_005f5 = (new org.apache.myfaces.taglib.html.HtmlCommandLinkTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fcommandLink_005f5);
    _jspx_th_h_005fcommandLink_005f5.setPageContext(_jspx_page_context);
    _jspx_th_h_005fcommandLink_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f5);
    // /index.jsp(46,3) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object myMethod(  )
    _jspx_th_h_005fcommandLink_005f5.setAction(new org.apache.jasper.el.JspMethodExpression("/index.jsp(46,3) '#{ordineController.listaOrdiniAdmin}'",_el_expressionfactory.createMethodExpression(_jspx_page_context.getELContext(),"#{ordineController.listaOrdiniAdmin}",java.lang.Object.class,new java.lang.Class[] {})));
    // /index.jsp(46,3) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005fcommandLink_005f5.setValue(new org.apache.jasper.el.JspValueExpression("/index.jsp(46,3) 'Consulta gli ordini'",_el_expressionfactory.createValueExpression("Consulta gli ordini",java.lang.Object.class)));
    _jspx_th_h_005fcommandLink_005f5.setJspId("jsp_20032806_12");
    int _jspx_eval_h_005fcommandLink_005f5 = _jspx_th_h_005fcommandLink_005f5.doStartTag();
    if (_jspx_eval_h_005fcommandLink_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005fcommandLink_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005fcommandLink_005f5.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005fcommandLink_005f5.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_h_005fcommandLink_005f5.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005fcommandLink_005f5 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005fcommandLink_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fcommandLink_005f5.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f5);
      return true;
    }
    _jspx_th_h_005fcommandLink_005f5.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
    // /index.jsp(50,24) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/faces/registraUtente.jsp");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
    // /index.jsp(51,24) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/faces/registraFornitore.jsp");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
    // /index.jsp(53,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${utenteController.corrente != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
    if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t<h1><center>");
        if (_jspx_meth_h_005fform_005f6(_jspx_th_c_005fif_005f5, _jspx_page_context))
          return true;
        out.write("</center></h1>\n");
        out.write("\t\t\t<h1><center>\n");
        out.write("\t\t\t");
        if (_jspx_meth_h_005fform_005f7(_jspx_th_c_005fif_005f5, _jspx_page_context))
          return true;
        out.write("</center></h1>\n");
        out.write("\t\t\t<h1><center>\n");
        out.write("\t\t\t");
        if (_jspx_meth_h_005fform_005f8(_jspx_th_c_005fif_005f5, _jspx_page_context))
          return true;
        out.write("</center></h1>\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:form
    org.apache.myfaces.taglib.html.HtmlFormTag _jspx_th_h_005fform_005f6 = (new org.apache.myfaces.taglib.html.HtmlFormTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fform_005f6);
    _jspx_th_h_005fform_005f6.setPageContext(_jspx_page_context);
    _jspx_th_h_005fform_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f5);
    _jspx_th_h_005fform_005f6.setJspId("jsp_20032806_13");
    int _jspx_eval_h_005fform_005f6 = _jspx_th_h_005fform_005f6.doStartTag();
    if (_jspx_eval_h_005fform_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005fform_005f6 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005fform_005f6.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005fform_005f6.doInitBody();
      }
      do {
        if (_jspx_meth_h_005fcommandLink_005f6(_jspx_th_h_005fform_005f6, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_h_005fform_005f6.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005fform_005f6 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005fform_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fform_005f6.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f6);
      return true;
    }
    _jspx_th_h_005fform_005f6.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f6);
    return false;
  }

  private boolean _jspx_meth_h_005fcommandLink_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f6, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandLink
    org.apache.myfaces.taglib.html.HtmlCommandLinkTag _jspx_th_h_005fcommandLink_005f6 = (new org.apache.myfaces.taglib.html.HtmlCommandLinkTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fcommandLink_005f6);
    _jspx_th_h_005fcommandLink_005f6.setPageContext(_jspx_page_context);
    _jspx_th_h_005fcommandLink_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f6);
    // /index.jsp(54,23) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object myMethod(  )
    _jspx_th_h_005fcommandLink_005f6.setAction(new org.apache.jasper.el.JspMethodExpression("/index.jsp(54,23) '#{productController.listProductsUser}'",_el_expressionfactory.createMethodExpression(_jspx_page_context.getELContext(),"#{productController.listProductsUser}",java.lang.Object.class,new java.lang.Class[] {})));
    // /index.jsp(54,23) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005fcommandLink_005f6.setValue(new org.apache.jasper.el.JspValueExpression("/index.jsp(54,23) 'Visita il Catalogo Prodotti'",_el_expressionfactory.createValueExpression("Visita il Catalogo Prodotti",java.lang.Object.class)));
    _jspx_th_h_005fcommandLink_005f6.setJspId("jsp_20032806_14");
    int _jspx_eval_h_005fcommandLink_005f6 = _jspx_th_h_005fcommandLink_005f6.doStartTag();
    if (_jspx_th_h_005fcommandLink_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fcommandLink_005f6.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f6);
      return true;
    }
    _jspx_th_h_005fcommandLink_005f6.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f6);
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:form
    org.apache.myfaces.taglib.html.HtmlFormTag _jspx_th_h_005fform_005f7 = (new org.apache.myfaces.taglib.html.HtmlFormTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fform_005f7);
    _jspx_th_h_005fform_005f7.setPageContext(_jspx_page_context);
    _jspx_th_h_005fform_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f5);
    _jspx_th_h_005fform_005f7.setJspId("jsp_20032806_15");
    int _jspx_eval_h_005fform_005f7 = _jspx_th_h_005fform_005f7.doStartTag();
    if (_jspx_eval_h_005fform_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005fform_005f7 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005fform_005f7.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005fform_005f7.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t\t\t");
        if (_jspx_meth_h_005fcommandLink_005f7(_jspx_th_h_005fform_005f7, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_h_005fform_005f7.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005fform_005f7 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005fform_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fform_005f7.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f7);
      return true;
    }
    _jspx_th_h_005fform_005f7.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f7);
    return false;
  }

  private boolean _jspx_meth_h_005fcommandLink_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f7, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandLink
    org.apache.myfaces.taglib.html.HtmlCommandLinkTag _jspx_th_h_005fcommandLink_005f7 = (new org.apache.myfaces.taglib.html.HtmlCommandLinkTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fcommandLink_005f7);
    _jspx_th_h_005fcommandLink_005f7.setPageContext(_jspx_page_context);
    _jspx_th_h_005fcommandLink_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f7);
    // /index.jsp(57,3) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object myMethod(  )
    _jspx_th_h_005fcommandLink_005f7.setAction(new org.apache.jasper.el.JspMethodExpression("/index.jsp(57,3) '#{ordineController.inizializzaOrdine}'",_el_expressionfactory.createMethodExpression(_jspx_page_context.getELContext(),"#{ordineController.inizializzaOrdine}",java.lang.Object.class,new java.lang.Class[] {})));
    // /index.jsp(57,3) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005fcommandLink_005f7.setValue(new org.apache.jasper.el.JspValueExpression("/index.jsp(57,3) 'Crea Nuovo Ordine'",_el_expressionfactory.createValueExpression("Crea Nuovo Ordine",java.lang.Object.class)));
    _jspx_th_h_005fcommandLink_005f7.setJspId("jsp_20032806_16");
    int _jspx_eval_h_005fcommandLink_005f7 = _jspx_th_h_005fcommandLink_005f7.doStartTag();
    if (_jspx_eval_h_005fcommandLink_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005fcommandLink_005f7 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005fcommandLink_005f7.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005fcommandLink_005f7.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_f_005fparam_005f0(_jspx_th_h_005fcommandLink_005f7, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_h_005fcommandLink_005f7.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005fcommandLink_005f7 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005fcommandLink_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fcommandLink_005f7.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f7);
      return true;
    }
    _jspx_th_h_005fcommandLink_005f7.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f7);
    return false;
  }

  private boolean _jspx_meth_f_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcommandLink_005f7, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:param
    org.apache.myfaces.taglib.core.ParamTag _jspx_th_f_005fparam_005f0 = (new org.apache.myfaces.taglib.core.ParamTag());
    _jsp_instancemanager.newInstance(_jspx_th_f_005fparam_005f0);
    _jspx_th_f_005fparam_005f0.setPageContext(_jspx_page_context);
    _jspx_th_f_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcommandLink_005f7);
    // /index.jsp(58,4) name = name type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_f_005fparam_005f0.setName(new org.apache.jasper.el.JspValueExpression("/index.jsp(58,4) 'uid'",_el_expressionfactory.createValueExpression("uid",java.lang.String.class)));
    // /index.jsp(58,4) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_f_005fparam_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/index.jsp(58,4) '#{utenteController.corrente.id}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"#{utenteController.corrente.id}",java.lang.Object.class)));
    _jspx_th_f_005fparam_005f0.setJspId("jsp_20032806_17");
    int _jspx_eval_f_005fparam_005f0 = _jspx_th_f_005fparam_005f0.doStartTag();
    if (_jspx_th_f_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_f_005fparam_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_f_005fparam_005f0);
      return true;
    }
    _jspx_th_f_005fparam_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_f_005fparam_005f0);
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:form
    org.apache.myfaces.taglib.html.HtmlFormTag _jspx_th_h_005fform_005f8 = (new org.apache.myfaces.taglib.html.HtmlFormTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fform_005f8);
    _jspx_th_h_005fform_005f8.setPageContext(_jspx_page_context);
    _jspx_th_h_005fform_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f5);
    _jspx_th_h_005fform_005f8.setJspId("jsp_20032806_18");
    int _jspx_eval_h_005fform_005f8 = _jspx_th_h_005fform_005f8.doStartTag();
    if (_jspx_eval_h_005fform_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005fform_005f8 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005fform_005f8.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005fform_005f8.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t\t\t");
        if (_jspx_meth_h_005fcommandLink_005f8(_jspx_th_h_005fform_005f8, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_h_005fform_005f8.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005fform_005f8 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005fform_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fform_005f8.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f8);
      return true;
    }
    _jspx_th_h_005fform_005f8.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f8);
    return false;
  }

  private boolean _jspx_meth_h_005fcommandLink_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f8, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandLink
    org.apache.myfaces.taglib.html.HtmlCommandLinkTag _jspx_th_h_005fcommandLink_005f8 = (new org.apache.myfaces.taglib.html.HtmlCommandLinkTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fcommandLink_005f8);
    _jspx_th_h_005fcommandLink_005f8.setPageContext(_jspx_page_context);
    _jspx_th_h_005fcommandLink_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f8);
    // /index.jsp(63,3) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object myMethod(  )
    _jspx_th_h_005fcommandLink_005f8.setAction(new org.apache.jasper.el.JspMethodExpression("/index.jsp(63,3) '#{ordineController.listaOrdini}'",_el_expressionfactory.createMethodExpression(_jspx_page_context.getELContext(),"#{ordineController.listaOrdini}",java.lang.Object.class,new java.lang.Class[] {})));
    // /index.jsp(63,3) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005fcommandLink_005f8.setValue(new org.apache.jasper.el.JspValueExpression("/index.jsp(63,3) 'Consulta i tuoi ordini'",_el_expressionfactory.createValueExpression("Consulta i tuoi ordini",java.lang.Object.class)));
    _jspx_th_h_005fcommandLink_005f8.setJspId("jsp_20032806_19");
    int _jspx_eval_h_005fcommandLink_005f8 = _jspx_th_h_005fcommandLink_005f8.doStartTag();
    if (_jspx_eval_h_005fcommandLink_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005fcommandLink_005f8 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005fcommandLink_005f8.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005fcommandLink_005f8.doInitBody();
      }
      do {
        out.write("\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_f_005fparam_005f1(_jspx_th_h_005fcommandLink_005f8, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_h_005fcommandLink_005f8.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005fcommandLink_005f8 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005fcommandLink_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fcommandLink_005f8.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f8);
      return true;
    }
    _jspx_th_h_005fcommandLink_005f8.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f8);
    return false;
  }

  private boolean _jspx_meth_f_005fparam_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcommandLink_005f8, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:param
    org.apache.myfaces.taglib.core.ParamTag _jspx_th_f_005fparam_005f1 = (new org.apache.myfaces.taglib.core.ParamTag());
    _jsp_instancemanager.newInstance(_jspx_th_f_005fparam_005f1);
    _jspx_th_f_005fparam_005f1.setPageContext(_jspx_page_context);
    _jspx_th_f_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcommandLink_005f8);
    // /index.jsp(64,4) name = name type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_f_005fparam_005f1.setName(new org.apache.jasper.el.JspValueExpression("/index.jsp(64,4) 'uid'",_el_expressionfactory.createValueExpression("uid",java.lang.String.class)));
    // /index.jsp(64,4) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_f_005fparam_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/index.jsp(64,4) '#{utenteController.corrente.id}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"#{utenteController.corrente.id}",java.lang.Object.class)));
    _jspx_th_f_005fparam_005f1.setJspId("jsp_20032806_20");
    int _jspx_eval_f_005fparam_005f1 = _jspx_th_f_005fparam_005f1.doStartTag();
    if (_jspx_th_f_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_f_005fparam_005f1.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_f_005fparam_005f1);
      return true;
    }
    _jspx_th_f_005fparam_005f1.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_f_005fparam_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
    // /index.jsp(68,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${amministratoreController.corrente == null && utenteController.corrente == null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
    if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t<h1><center><a href='");
        if (_jspx_meth_c_005furl_005f3(_jspx_th_c_005fif_005f6, _jspx_page_context))
          return true;
        out.write("'>Effettua il login Utente</a></center></h1>\n");
        out.write("\t\t\t<h1><center><a href='");
        if (_jspx_meth_c_005furl_005f4(_jspx_th_c_005fif_005f6, _jspx_page_context))
          return true;
        out.write("'>Effettua il login Amministratore</a></center></h1>\t\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f6, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f6);
    // /index.jsp(69,24) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/faces/loginUtente.jsp");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f6, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f6);
    // /index.jsp(70,24) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f4.setValue("/faces/loginAmministratore.jsp");
    int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
    if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
    // /index.jsp(75,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f5.setValue("/faces/newProduct.jsp");
    int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
    if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:form
    org.apache.myfaces.taglib.html.HtmlFormTag _jspx_th_h_005fform_005f9 = (new org.apache.myfaces.taglib.html.HtmlFormTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fform_005f9);
    _jspx_th_h_005fform_005f9.setPageContext(_jspx_page_context);
    _jspx_th_h_005fform_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
    _jspx_th_h_005fform_005f9.setJspId("jsp_20032806_21");
    int _jspx_eval_h_005fform_005f9 = _jspx_th_h_005fform_005f9.doStartTag();
    if (_jspx_eval_h_005fform_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005fform_005f9 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005fform_005f9.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005fform_005f9.doInitBody();
      }
      do {
        if (_jspx_meth_h_005fcommandLink_005f9(_jspx_th_h_005fform_005f9, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_h_005fform_005f9.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005fform_005f9 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005fform_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fform_005f9.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f9);
      return true;
    }
    _jspx_th_h_005fform_005f9.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f9);
    return false;
  }

  private boolean _jspx_meth_h_005fcommandLink_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f9, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandLink
    org.apache.myfaces.taglib.html.HtmlCommandLinkTag _jspx_th_h_005fcommandLink_005f9 = (new org.apache.myfaces.taglib.html.HtmlCommandLinkTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fcommandLink_005f9);
    _jspx_th_h_005fcommandLink_005f9.setPageContext(_jspx_page_context);
    _jspx_th_h_005fcommandLink_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f9);
    // /index.jsp(76,15) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object myMethod(  )
    _jspx_th_h_005fcommandLink_005f9.setAction(new org.apache.jasper.el.JspMethodExpression("/index.jsp(76,15) '#{productController.listProducts}'",_el_expressionfactory.createMethodExpression(_jspx_page_context.getELContext(),"#{productController.listProducts}",java.lang.Object.class,new java.lang.Class[] {})));
    // /index.jsp(76,15) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005fcommandLink_005f9.setValue(new org.apache.jasper.el.JspValueExpression("/index.jsp(76,15) 'Visualizza la base di dati dei prodotti'",_el_expressionfactory.createValueExpression("Visualizza la base di dati dei prodotti",java.lang.Object.class)));
    _jspx_th_h_005fcommandLink_005f9.setJspId("jsp_20032806_22");
    int _jspx_eval_h_005fcommandLink_005f9 = _jspx_th_h_005fcommandLink_005f9.doStartTag();
    if (_jspx_th_h_005fcommandLink_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fcommandLink_005f9.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f9);
      return true;
    }
    _jspx_th_h_005fcommandLink_005f9.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f9);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
    // /index.jsp(77,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f6.setValue("/faces/registraAmministratore.jsp");
    int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
    if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
    return false;
  }
}
