/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat (TomEE)/7.0.55 (1.7.1)
 * Generated at: 2015-05-13 07:29:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class newProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fview;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fform;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005frequiredMessage_005frequired_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fmessage_0026_005ffor_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005frequiredMessage_005frequired_005fid_005fconverterMessage_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005finputTextarea_0026_005fvalue_005frows_005frequired_005fcols_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fcommandButton_0026_005fvalue_005faction_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fcommandLink_0026_005fvalue_005faction_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ff_005fview = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fform = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005frequiredMessage_005frequired_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fmessage_0026_005ffor_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005frequiredMessage_005frequired_005fid_005fconverterMessage_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005finputTextarea_0026_005fvalue_005frows_005frequired_005fcols_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fcommandButton_0026_005fvalue_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fcommandLink_0026_005fvalue_005faction_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ff_005fview.release();
    _005fjspx_005ftagPool_005fh_005fform.release();
    _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005frequiredMessage_005frequired_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005fmessage_0026_005ffor_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005finputText_0026_005fvalue_005frequiredMessage_005frequired_005fid_005fconverterMessage_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005finputTextarea_0026_005fvalue_005frows_005frequired_005fcols_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005fcommandButton_0026_005fvalue_005faction_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005fcommandLink_0026_005fvalue_005faction_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=US-ASCII");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=US-ASCII\">\n");
      out.write("<title>New Product</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      if (_jspx_meth_f_005fview_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_f_005fview_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:view
    org.apache.myfaces.taglib.core.ViewTag _jspx_th_f_005fview_005f0 = (new org.apache.myfaces.taglib.core.ViewTag());
    _jsp_instancemanager.newInstance(_jspx_th_f_005fview_005f0);
    _jspx_th_f_005fview_005f0.setPageContext(_jspx_page_context);
    _jspx_th_f_005fview_005f0.setParent(null);
    _jspx_th_f_005fview_005f0.setJspId("jsp_1996844384_0");
    int _jspx_eval_f_005fview_005f0 = _jspx_th_f_005fview_005f0.doStartTag();
    if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_f_005fview_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_f_005fview_005f0.doInitBody();
      }
      do {
        out.write('\n');
        if (_jspx_meth_h_005fform_005f0(_jspx_th_f_005fview_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        int evalDoAfterBody = _jspx_th_f_005fview_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_f_005fview_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_f_005fview_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_f_005fview_005f0);
      return true;
    }
    _jspx_th_f_005fview_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_f_005fview_005f0);
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:form
    org.apache.myfaces.taglib.html.HtmlFormTag _jspx_th_h_005fform_005f0 = (new org.apache.myfaces.taglib.html.HtmlFormTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fform_005f0);
    _jspx_th_h_005fform_005f0.setPageContext(_jspx_page_context);
    _jspx_th_h_005fform_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
    _jspx_th_h_005fform_005f0.setJspId("jsp_1996844384_1");
    int _jspx_eval_h_005fform_005f0 = _jspx_th_h_005fform_005f0.doStartTag();
    if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_h_005fform_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_h_005fform_005f0.doInitBody();
      }
      do {
        out.write("\n");
        out.write("    <div>Name: ");
        if (_jspx_meth_h_005finputText_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
          return true;
        out.write(' ');
        if (_jspx_meth_h_005fmessage_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t</div>\n");
        out.write("    <div>Code: ");
        if (_jspx_meth_h_005finputText_005f1(_jspx_th_h_005fform_005f0, _jspx_page_context))
          return true;
        out.write(' ');
        if (_jspx_meth_h_005fmessage_005f1(_jspx_th_h_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t</div>\n");
        out.write("    <div>Price: ");
        if (_jspx_meth_h_005finputText_005f2(_jspx_th_h_005fform_005f0, _jspx_page_context))
          return true;
        out.write(' ');
        if (_jspx_meth_h_005fmessage_005f2(_jspx_th_h_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t</div>\n");
        out.write("    <div>Description: ");
        if (_jspx_meth_h_005finputTextarea_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
          return true;
        out.write(" \n");
        out.write("                     \n");
        out.write("\t</div>\n");
        out.write("\t<div>\n");
        out.write("\t\t");
        if (_jspx_meth_h_005fcommandButton_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t</div>\n");
        out.write("\t");
        if (_jspx_meth_h_005fcommandLink_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        int evalDoAfterBody = _jspx_th_h_005fform_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_h_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fform_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f0);
      return true;
    }
    _jspx_th_h_005fform_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fform_005f0);
    return false;
  }

  private boolean _jspx_meth_h_005finputText_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:inputText
    org.apache.myfaces.taglib.html.HtmlInputTextTag _jspx_th_h_005finputText_005f0 = (new org.apache.myfaces.taglib.html.HtmlInputTextTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005finputText_005f0);
    _jspx_th_h_005finputText_005f0.setPageContext(_jspx_page_context);
    _jspx_th_h_005finputText_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
    // /newProduct.jsp(13,15) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005finputText_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(13,15) '#{productController.name}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"#{productController.name}",java.lang.Object.class)));
    // /newProduct.jsp(13,15) name = required type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = boolean deferredMethod = false methodSignature = null
    _jspx_th_h_005finputText_005f0.setRequired(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(13,15) 'true'",_el_expressionfactory.createValueExpression("true",boolean.class)));
    // /newProduct.jsp(13,15) name = requiredMessage type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_h_005finputText_005f0.setRequiredMessage(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(13,15) 'Name is mandatory'",_el_expressionfactory.createValueExpression("Name is mandatory",java.lang.String.class)));
    // /newProduct.jsp(13,15) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_h_005finputText_005f0.setId("name");
    _jspx_th_h_005finputText_005f0.setJspId("jsp_1996844384_2");
    int _jspx_eval_h_005finputText_005f0 = _jspx_th_h_005finputText_005f0.doStartTag();
    if (_jspx_th_h_005finputText_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005finputText_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005finputText_005f0);
      return true;
    }
    _jspx_th_h_005finputText_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005finputText_005f0);
    return false;
  }

  private boolean _jspx_meth_h_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:message
    org.apache.myfaces.taglib.html.HtmlMessageTag _jspx_th_h_005fmessage_005f0 = (new org.apache.myfaces.taglib.html.HtmlMessageTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fmessage_005f0);
    _jspx_th_h_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_h_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
    // /newProduct.jsp(16,33) name = for type = javax.el.ValueExpression reqTime = false required = true fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_h_005fmessage_005f0.setFor(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(16,33) 'name'",_el_expressionfactory.createValueExpression("name",java.lang.String.class)));
    _jspx_th_h_005fmessage_005f0.setJspId("jsp_1996844384_3");
    int _jspx_eval_h_005fmessage_005f0 = _jspx_th_h_005fmessage_005f0.doStartTag();
    if (_jspx_th_h_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fmessage_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fmessage_005f0);
      return true;
    }
    _jspx_th_h_005fmessage_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_h_005finputText_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:inputText
    org.apache.myfaces.taglib.html.HtmlInputTextTag _jspx_th_h_005finputText_005f1 = (new org.apache.myfaces.taglib.html.HtmlInputTextTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005finputText_005f1);
    _jspx_th_h_005finputText_005f1.setPageContext(_jspx_page_context);
    _jspx_th_h_005finputText_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
    // /newProduct.jsp(18,15) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005finputText_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(18,15) '#{productController.code}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"#{productController.code}",java.lang.Object.class)));
    // /newProduct.jsp(18,15) name = required type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = boolean deferredMethod = false methodSignature = null
    _jspx_th_h_005finputText_005f1.setRequired(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(18,15) 'true'",_el_expressionfactory.createValueExpression("true",boolean.class)));
    // /newProduct.jsp(18,15) name = requiredMessage type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_h_005finputText_005f1.setRequiredMessage(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(18,15) 'Code is mandatory'",_el_expressionfactory.createValueExpression("Code is mandatory",java.lang.String.class)));
    // /newProduct.jsp(18,15) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_h_005finputText_005f1.setId("code");
    _jspx_th_h_005finputText_005f1.setJspId("jsp_1996844384_4");
    int _jspx_eval_h_005finputText_005f1 = _jspx_th_h_005finputText_005f1.doStartTag();
    if (_jspx_th_h_005finputText_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005finputText_005f1.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005finputText_005f1);
      return true;
    }
    _jspx_th_h_005finputText_005f1.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005finputText_005f1);
    return false;
  }

  private boolean _jspx_meth_h_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:message
    org.apache.myfaces.taglib.html.HtmlMessageTag _jspx_th_h_005fmessage_005f1 = (new org.apache.myfaces.taglib.html.HtmlMessageTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fmessage_005f1);
    _jspx_th_h_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_h_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
    // /newProduct.jsp(21,33) name = for type = javax.el.ValueExpression reqTime = false required = true fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_h_005fmessage_005f1.setFor(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(21,33) 'code'",_el_expressionfactory.createValueExpression("code",java.lang.String.class)));
    _jspx_th_h_005fmessage_005f1.setJspId("jsp_1996844384_5");
    int _jspx_eval_h_005fmessage_005f1 = _jspx_th_h_005fmessage_005f1.doStartTag();
    if (_jspx_th_h_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fmessage_005f1.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fmessage_005f1);
      return true;
    }
    _jspx_th_h_005fmessage_005f1.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fmessage_005f1);
    return false;
  }

  private boolean _jspx_meth_h_005finputText_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:inputText
    org.apache.myfaces.taglib.html.HtmlInputTextTag _jspx_th_h_005finputText_005f2 = (new org.apache.myfaces.taglib.html.HtmlInputTextTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005finputText_005f2);
    _jspx_th_h_005finputText_005f2.setPageContext(_jspx_page_context);
    _jspx_th_h_005finputText_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
    // /newProduct.jsp(23,16) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005finputText_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(23,16) '#{productController.price}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"#{productController.price}",java.lang.Object.class)));
    // /newProduct.jsp(23,16) name = required type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = boolean deferredMethod = false methodSignature = null
    _jspx_th_h_005finputText_005f2.setRequired(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(23,16) 'true'",_el_expressionfactory.createValueExpression("true",boolean.class)));
    // /newProduct.jsp(23,16) name = requiredMessage type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_h_005finputText_005f2.setRequiredMessage(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(23,16) 'Price is mandatory'",_el_expressionfactory.createValueExpression("Price is mandatory",java.lang.String.class)));
    // /newProduct.jsp(23,16) name = converterMessage type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_h_005finputText_005f2.setConverterMessage(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(23,16) 'Price must be a number'",_el_expressionfactory.createValueExpression("Price must be a number",java.lang.String.class)));
    // /newProduct.jsp(23,16) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_h_005finputText_005f2.setId("price");
    _jspx_th_h_005finputText_005f2.setJspId("jsp_1996844384_6");
    int _jspx_eval_h_005finputText_005f2 = _jspx_th_h_005finputText_005f2.doStartTag();
    if (_jspx_th_h_005finputText_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005finputText_005f2.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005finputText_005f2);
      return true;
    }
    _jspx_th_h_005finputText_005f2.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005finputText_005f2);
    return false;
  }

  private boolean _jspx_meth_h_005fmessage_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:message
    org.apache.myfaces.taglib.html.HtmlMessageTag _jspx_th_h_005fmessage_005f2 = (new org.apache.myfaces.taglib.html.HtmlMessageTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fmessage_005f2);
    _jspx_th_h_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_h_005fmessage_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
    // /newProduct.jsp(27,34) name = for type = javax.el.ValueExpression reqTime = false required = true fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_h_005fmessage_005f2.setFor(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(27,34) 'price'",_el_expressionfactory.createValueExpression("price",java.lang.String.class)));
    _jspx_th_h_005fmessage_005f2.setJspId("jsp_1996844384_7");
    int _jspx_eval_h_005fmessage_005f2 = _jspx_th_h_005fmessage_005f2.doStartTag();
    if (_jspx_th_h_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fmessage_005f2.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fmessage_005f2);
      return true;
    }
    _jspx_th_h_005fmessage_005f2.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fmessage_005f2);
    return false;
  }

  private boolean _jspx_meth_h_005finputTextarea_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:inputTextarea
    org.apache.myfaces.taglib.html.HtmlInputTextareaTag _jspx_th_h_005finputTextarea_005f0 = (new org.apache.myfaces.taglib.html.HtmlInputTextareaTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005finputTextarea_005f0);
    _jspx_th_h_005finputTextarea_005f0.setPageContext(_jspx_page_context);
    _jspx_th_h_005finputTextarea_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
    // /newProduct.jsp(29,22) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005finputTextarea_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(29,22) '#{productController.description}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"#{productController.description}",java.lang.Object.class)));
    // /newProduct.jsp(29,22) name = required type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = boolean deferredMethod = false methodSignature = null
    _jspx_th_h_005finputTextarea_005f0.setRequired(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(29,22) 'false'",_el_expressionfactory.createValueExpression("false",boolean.class)));
    // /newProduct.jsp(29,22) name = cols type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = int deferredMethod = false methodSignature = null
    _jspx_th_h_005finputTextarea_005f0.setCols(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(29,22) '20'",_el_expressionfactory.createValueExpression("20",int.class)));
    // /newProduct.jsp(29,22) name = rows type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = int deferredMethod = false methodSignature = null
    _jspx_th_h_005finputTextarea_005f0.setRows(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(29,22) '5'",_el_expressionfactory.createValueExpression("5",int.class)));
    _jspx_th_h_005finputTextarea_005f0.setJspId("jsp_1996844384_8");
    int _jspx_eval_h_005finputTextarea_005f0 = _jspx_th_h_005finputTextarea_005f0.doStartTag();
    if (_jspx_th_h_005finputTextarea_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005finputTextarea_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005finputTextarea_005f0);
      return true;
    }
    _jspx_th_h_005finputTextarea_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005finputTextarea_005f0);
    return false;
  }

  private boolean _jspx_meth_h_005fcommandButton_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandButton
    org.apache.myfaces.taglib.html.HtmlCommandButtonTag _jspx_th_h_005fcommandButton_005f0 = (new org.apache.myfaces.taglib.html.HtmlCommandButtonTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fcommandButton_005f0);
    _jspx_th_h_005fcommandButton_005f0.setPageContext(_jspx_page_context);
    _jspx_th_h_005fcommandButton_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
    // /newProduct.jsp(36,2) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005fcommandButton_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(36,2) 'Submit'",_el_expressionfactory.createValueExpression("Submit",java.lang.Object.class)));
    // /newProduct.jsp(36,2) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object myMethod(  )
    _jspx_th_h_005fcommandButton_005f0.setAction(new org.apache.jasper.el.JspMethodExpression("/newProduct.jsp(36,2) '#{productController.createProduct}'",_el_expressionfactory.createMethodExpression(_jspx_page_context.getELContext(),"#{productController.createProduct}",java.lang.Object.class,new java.lang.Class[] {})));
    _jspx_th_h_005fcommandButton_005f0.setJspId("jsp_1996844384_9");
    int _jspx_eval_h_005fcommandButton_005f0 = _jspx_th_h_005fcommandButton_005f0.doStartTag();
    if (_jspx_th_h_005fcommandButton_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fcommandButton_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandButton_005f0);
      return true;
    }
    _jspx_th_h_005fcommandButton_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandButton_005f0);
    return false;
  }

  private boolean _jspx_meth_h_005fcommandLink_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:commandLink
    org.apache.myfaces.taglib.html.HtmlCommandLinkTag _jspx_th_h_005fcommandLink_005f0 = (new org.apache.myfaces.taglib.html.HtmlCommandLinkTag());
    _jsp_instancemanager.newInstance(_jspx_th_h_005fcommandLink_005f0);
    _jspx_th_h_005fcommandLink_005f0.setPageContext(_jspx_page_context);
    _jspx_th_h_005fcommandLink_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
    // /newProduct.jsp(38,1) name = action type = javax.el.MethodExpression reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = true methodSignature = java.lang.Object myMethod(  )
    _jspx_th_h_005fcommandLink_005f0.setAction(new org.apache.jasper.el.JspMethodExpression("/newProduct.jsp(38,1) '#{productController.listProducts}'",_el_expressionfactory.createMethodExpression(_jspx_page_context.getELContext(),"#{productController.listProducts}",java.lang.Object.class,new java.lang.Class[] {})));
    // /newProduct.jsp(38,1) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_h_005fcommandLink_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/newProduct.jsp(38,1) 'List all Products'",_el_expressionfactory.createValueExpression("List all Products",java.lang.Object.class)));
    _jspx_th_h_005fcommandLink_005f0.setJspId("jsp_1996844384_10");
    int _jspx_eval_h_005fcommandLink_005f0 = _jspx_th_h_005fcommandLink_005f0.doStartTag();
    if (_jspx_th_h_005fcommandLink_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _jspx_th_h_005fcommandLink_005f0.release();
      _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f0);
      return true;
    }
    _jspx_th_h_005fcommandLink_005f0.release();
    _jsp_instancemanager.destroyInstance(_jspx_th_h_005fcommandLink_005f0);
    return false;
  }
}
